//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbViewsEntities : DbContext
    {
        public dbViewsEntities()
            : base("name=dbViewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwadminlog> vwadminlogs { get; set; }
        public DbSet<vwbranch> vwbranches { get; set; }
        public DbSet<vwdistrib> vwdistribs { get; set; }
        public DbSet<vwfacultylog> vwfacultylogs { get; set; }
        public DbSet<vwitem> vwitems { get; set; }
        public DbSet<vwlog> vwlogs { get; set; }
        public DbSet<vwmanufacturer> vwmanufacturers { get; set; }
        public DbSet<vwreceived> vwreceiveds { get; set; }
        public DbSet<vwstock> vwstocks { get; set; }
        public DbSet<vwstudentlog> vwstudentlogs { get; set; }
        public DbSet<vwsupplier> vwsuppliers { get; set; }
        public DbSet<vwreportlistofitem> vwreportlistofitems { get; set; }
    }
}
