//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwdistrib
    {
        public string DistCode { get; set; }
        public string Branch { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Item_Name { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public System.DateTime Date { get; set; }
    }
}
