//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwreceived
    {
        public string Receiving_Code { get; set; }
        public string Item { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public string Supplier { get; set; }
        public System.DateTime Date_Received { get; set; }
    }
}
