//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwreportlistofitem
    {
        public string Item_Type { get; set; }
        public string Name { get; set; }
        public string Generic_Name { get; set; }
        public string Manufacturer { get; set; }
    }
}
