//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwstock
    {
        public string Code { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Consumed { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
