//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUPiMed.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwstudentlog
    {
        public string Code { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Course__Year___Section { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
    }
}
